### PR TITLE
GiST support

### PR DESCRIPTION
**Pull request by x4m**
Hi!

Here is a prototype for GiST check that checks graph compliance with RTContainedBy strategy.
It should hold...but not every type has this strategy. For example, point type has no defined <@ operator.
Maybe I should better use adjustment function and check that insertion of a child tuple do not adjust parent anyhow.

I do not expect this to be committed, this is a prototype for discussion.

### CODE REVIEW

**Comment by petergeoghegan** [comment]
@x4m Would you be willing to submit this as a patch for Postgres v12?

**Comment by x4m** [comment]
Yep, planning to do so.

**Comment by petergeoghegan** [comment]
It may make more sense to get some review on the list first. I'm not suggesting that a PostgreSQL commit should be a blocker to merging your PR, but it would be nice to get some review from someone that knows more about GiST than I do. I don't know very much about it.

What do you think?

**Comment by x4m** [comment]
Yeah, I think that posting this to pgsql-hackers is a way to go if the separate function for GiST is in alignment with the overall amcheck idea. I think I'll add heap all indexed too before posting. It's there in a separate branch already but still not functional.
Maybe I should also add check that every GiST page with data is accessible from another page...

Anyway, there's whole summer before next CF, I think I'll have some spare time to work in this direction.

**Comment by petergeoghegan** [comment]
The fact is that I don't know terribly much about GiST. I could spend time learning more on it, in order to maintain this code, but I'd prefer to get input on your design from hackers that know more about it already.

I'm sorry that I haven't been able to handle contributions very efficiently, but I've been very busy with other stuff.

**Comment by x4m** [comment]
That "other stuff" is also very important for me too :)
How do you see the future of amcheck? Should it be just like chkdsk with progress tracking and, possibly, some repair functions or should it be aimed at advancing AMs with new features? Someday we will implement things like LSM and Bw-tree...
I've copied interface for GiST from B-tree, is it correct direction?

**Comment by petergeoghegan** [comment]
I think that amcheck has both of those two things as goals (I always try to have at least 2 high-level goals for undertaking a project, and will ideally have several).

I don't see repair as a viable idea. There is no point in having something like zero_damaged_pages for indexes, because you can always REINDEX. I have no idea how to repair corruption, because corruption should only occur due to a factor that nobody could have foreseen. There might be some extremely rare exceptions, like a tool that specifically repairs the limited mechanical corruption produced by the Postgres bug fixed in 38b41f182a66b67e36e2adf53d078599b1b65483. These exceptional cases actually seem to strengthen rather than weaken my argument. Who is unlucky enough to get database corruption, but still lucky enough that the corruption is entirely reversible with a mechanical tool? That's a very tight band of (un)luckiness.

This is why ZFS does not have fsck. It just seems like a waste of time to try to repair corruption after the fact, when so much more can be done on the prevention side. A Gunawi et al. OSDI 08 paper finds that fsck “checks and repairs certain pointers in an incorrect order . . . the file system can even be unmountable after”, so I'm hardly the only one with this opinion.

I think you were right to copy the interface. There will be new interfaces in the future, but I think we'll always want an analogous interface to indexes of other AMs.

**Comment by petergeoghegan** [comment]
@x4m I don't see this in the current Postgres Commitfest. What's the plan there?

**Comment by x4m** [comment]
@petergeoghegan I can review only 1-2 patches per CF, so I keep count of my patches on CF 1-2...maybe 1-3 from time to time. I plan to post this on November CF if I will be able to review more or something from by patches will get committed.
Also, there is no heap_all_indexed in this patch, I have a version with this feature but it segfaults from time to time.
Thanks for your interest in this patch :)

**Comment by petergeoghegan** [comment]
@x4m I am interested. It's just a bit hectic right now. And like I said, we don't have to wait on -hackers to merge this here.

**Comment by x4m** [comment]
I've created a discussion thread for this
https://www.postgresql.org/message-id/59D0DA6B-1652-4D44-B0EF-A582D5824F83%40yandex-team.ru
and CF entry
https://commitfest.postgresql.org/20/1800/

**Comment by petergeoghegan** [comment]
I'm going to close this for now. When we have the patch in good shape on -hackers, please reopen the PR. I'll probably be able to commit it to contrib/amcheck myself, leaving the follow-up work here pretty straightforward integration work.

Thanks

**Pull request closed without merging**
